on:
  push:
    branches: [master]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [master]
  schedule:
    - cron: '0 22 * * 2'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up the Zig compiler
      - name: Setup Zig Compiler
        uses: mlugg/setup-zig@v2
        with:
          version: 0.15.1 # Specify the Zig version you need

      # Step 3: Build the Zig binary
      - name: Build Zig Binary
        run: |
          cd server
          # zig build -Dcpu=baseline -Doptimize=ReleaseSafe -freference-trace=11 -Dpie=true -Drelro=true -Dsystem_libs=false
          zig build -Dcpu=baseline -Doptimize=Debug -freference-trace=11 -Dpie=true -Drelro=true -Dsystem_libs=false
          sudo cp zig-out/bin/klutshnikd /usr/bin

      # Step 4: build libklutshnik and test
      - run: |
         sudo apt update
         sudo apt install -y libsodium-dev pkgconf # build-essential git python3-pip
         # liboprf
         git clone https://github.com/stef/liboprf/
         cd liboprf/src
         sudo mkdir -p /usr/include/oprf/
         sudo PREFIX=/usr make install
         # pyoprf
         pip3 install ../python/
         cd ../..
         # libklutshnik
         sudo PREFIX=/usr make install
         # klutshnik
         pip3 install python/
         sudo ldconfig
         cd test
         KLUTSHNIKD=/usr/bin/klutshnikd python3 -m unittest discover -fcb -v .

      - name: Archive Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test/servers

      # Step 4: Upload the binary as an artifact (optional)
      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: klutshnikd-static
          path: server/zig-out/bin/klutshnikd
